name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requisitos.txt
    - name: Run bot
      # Setting the DISCORD_TOKEN secret as an environment variable
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        main.py
